name: daily-skkni
on:
  schedule:
    - cron: "5 0 * * *"   # 07:05 WIB (UTC+7) == 00:05 UTC
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Write Google creds from secret
        run: |
          echo "$GSHEETS_JSON" > creds.json
        env:
          GSHEETS_JSON: ${{ secrets.GSHEETS_JSON }}

      - name: Run script
        env:
          SERPAPI_API_KEY: ${{ secrets.SERPAPI_API_KEY }}
          INPUT_GID: "372282629"
          OUTPUT_GID: "372282629"
          SHEET_KEY: "1EJqpHxeZz1CDt9qbZOXEW6Bm8MGVU1KQjiTeQiGh3GU"
        run: |
          python main.py

      # --- Email alert via Brevo if any "Dicabut" was found ---
      - name: Read alert text (if any)
        id: alert_txt
        if: hashFiles('alerts/dicabut_summary.txt') != ''
        run: |
          echo "text<<EOF" >> $GITHUB_OUTPUT
          cat alerts/dicabut_summary.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Send email if Dicabut found
        if: hashFiles('alerts/dicabut_summary.txt') != ''
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp-relay.brevo.com
          server_port: 587
          secure: false
          username: ${{ secrets.MAIL_USERNAME }}   # e.g., 9487f3001@smtp-brevo.com
          password: ${{ secrets.MAIL_PASSWORD }}   # your Brevo API key
          subject: "SKKNI Validator Alert: DICABUT ditemukan"
          from: "SKKNI Validator <${{ secrets.MAIL_USERNAME }}>"
          to: ${{ secrets.MAIL_TO }}               # comma-separated list
          body: ${{ steps.alert_txt.outputs.text }}

      - name: Upload alert artifact (optional)
        if: hashFiles('alerts/dicabut_summary.txt') != ''
        uses: actions/upload-artifact@v4
        with:
          name: dicabut-summary
          path: alerts/dicabut_summary.txt
